name: Deploy to Public Branch

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Checkout the public branch where files will be copied
      - name: Checkout public branch
        uses: actions/checkout@v3
        with:
          ref: public
          path: public

      # Step 3: Disable Jekyll by adding .nojekyll file
      - name: Disable Jekyll build
        run: |
          touch public/.nojekyll

      # Step 4: Sync files from the `output` folder of the main branch to the public branch
      - name: Sync output folder to public branch
        run: |
          rsync -av --exclude='.git' --exclude='.github' output/ public/

      # Step 5: Commit and push changes to the public branch
      - name: Commit and push changes
        run: |
          cd public
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync output folder content from main to public branch"
          git push origin public
