name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure we have the latest gh-pages branch
      - name: Checkout gh-pages branch
        run: |
          git fetch --all
          git checkout gh-pages || git checkout --orphan gh-pages

      # Step 3: Copy the contents of the Output folder to docs
      - name: Copy Output to docs folder
        run: |
          # Remove everything in the docs folder if it exists
          rm -rf docs/*

          # Copy files from Output to docs
          cp -r Output/* docs/

      # Step 4: Commit and push changes to gh-pages branch
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Deploy website to docs folder"
          git push origin gh-pages --force
