name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this on a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # Checkout the main branch

      - name: Checkout gh-pages branch
        run: |
          git fetch --all
          git checkout gh-pages || git checkout --orphan gh-pages  # Create or switch to the gh-pages branch

      - name: Clean up gh-pages folder
        run: |
          rm -rf *  # Clean the folder to prepare for new files

      - name: Copy files from output to gh-pages
        run: |
          cp -r output/* .  # Copy all files from the output folder (on the main branch) to the root of gh-pages

      - name: Create .nojekyll file
        run: |
          touch .nojekyll  # Create a .nojekyll file to disable Jekyll processing

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add . .nojekyll
          git commit -m "Deploy static files from main branch output"
          git push origin gh-pages --force
