name: Deploy to Public Branch

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Checkout the public branch as well
      - name: Checkout public branch
        uses: actions/checkout@v3
        with:
          ref: public
          path: public

      # Copy the content of the `output` folder from main branch to public branch
      - name: Copy output folder content
        run: |
          cp -r output/* public/

      # Commit and push changes to the public branch
      - name: Commit and push changes
        run: |
          cd public
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy output folder to public branch"
          git push origin public
