name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the personal access token
          publish_dir: ./output
          publish_branch: gh-pages
          user_name: 'github-actions'
          user_email: 'github-actions@github.com'
          commit_message: 'Deploy static site to GitHub Pages'
